# Generated by Django 4.2 on 2026-02-13 19:47

import core.validators
from django.db import migrations, models
import sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionimage',
            name='image',
            field=models.ImageField(upload_to=sellers.models.submission_image_upload_path, validators=[core.validators.validate_image_file, core.validators.validate_image_content_type]),
        ),
    ]
