# Generated by Django 4.2 on 2026-02-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        ('products', '0003_product_stock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='inspections.inspection'),
        ),
    ]
