# Generated by Django 4.2 on 2026-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_warranty_months',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='product',
            name='is_warranty_available',
            field=models.BooleanField(default=True),
        ),
    ]
